config/routes.rb
Rails.application.routes.draw do
  namespace :challenge_days do
    get ':challenge_day_id/photos/show/', to: 'photos#show', as: 'photo'
  end

  resources :challenges do
    scope module: 'challenges' do
      resources :months, only: [:index]
      # Write show route by hand so that I can use
      # params[:month] in the controller.
      get '/months/:month', to: 'months#show', as: 'month'
    end
  end
  root 'challenges#index'
  resources :challenge_days
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
  has_many :challenge_days

  after_create :create_challenge_days

  private

  def create_challenge_days
    (start_date..end_date).each do |date|
      ChallengeDay.create(date: date, challenge: self)
    end
  end
end

app/models/challenge_day.rb
class ChallengeDay < ApplicationRecord
  has_many_attached :images
  belongs_to :challenge
  enum :status, [ :neutral, :success, :fail ], default: :neutral
end

app/models/user.rb
class User < ApplicationRecord
  has_many :challenges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      unless (user = User.find_by_name(username.downcase)) && (password == 'muuji')
        render plain: 'Authorization Failed', status: :unauthorized
        return
      end
      session[:user_id] = user.id
    end
  end
end

app/controllers/challenge_days/photos_controller.rb
class ChallengeDays::PhotosController < ApplicationController
  def show
    @challenge_day = ChallengeDay.find_by(id: params[:challenge_day_id])
  end
end

app/controllers/challenge_days_controller.rb
class ChallengeDaysController < ApplicationController
  def edit
    @challenge_day = ChallengeDay.find_by id: params[:id]
  end

  def update
    @challenge_day = ChallengeDay.find_by id: params[:id]
    if @challenge_day
      @challenge_day.images.attach(params.dig(:challenge_day, :photo))
      @challenge_day.update challenge_day_params
    end
  end

  private

  def challenge_day_params
    params.require(:challenge_day).permit(:status, :note)
  end
end

app/controllers/challenges/months_controller.rb
class Challenges::MonthsController < ApplicationController
  def index
    @challenge = Challenge.find_by id: params[:challenge_id]
    @months = @challenge.challenge_days.pluck(:date).map {|d| d.month}.uniq
  end

  def show
    @challenge = Challenge.find_by id: params[:challenge_id]
    @challenge_days = @challenge.challenge_days.with_attached_images.group_by {|cd| cd.date.month}[params[:month].to_i]
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :user

  def index
    @challenges = Challenge.all
  end

  private

  def user
    User.find_by_id session[:user_id]
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  include LogsHelper

  def index
    @repo = 'https://github.com/binarygit/show-job'
    @commits = File.read('show-job.log').scan(/commit.+\n.+\n.+\n\n.+/)
    @message = "Showing all commits"
  end

  def create
    date = Date.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
    @commits = File.read('show-job.log').scan(/commit.+\n.+\n.+\n\n.+/)
    @commits = commits_on_date(date, @commits)
    @message = "Showing commits on #{date}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenge_days/photos_helper.rb
module ChallengeDays::PhotosHelper
end

app/helpers/challenge_days_helper.rb
module ChallengeDaysHelper
end

app/helpers/challenges/months_helper.rb
module Challenges::MonthsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
  def author(commit)
    commit.scan(/Author[^>]+>/).first.gsub(/Author: /, '').strip
  end

  def message(commit)
    commit.match(/\n\n.+/).to_s.strip
  end

  def dates(commits)
    commits.map { Date.parse(_1.match(/Date[^\+]+/).to_s.gsub(/Date:/, '').strip) }.uniq
  end

  def commits_on_date(date, commits)
    commits.select do |commit|
      date == get_date(commit)
    end
  end

  private

  def get_date(commit)
    commit.scan(/Date[^\+]+/).map { Date.parse(_1.gsub(/Date:/, '').strip) }.first
  end
end

app/views/challenge_days/edit.html.erb
<%= render(::ChallengeDay::ChallengeDayNeutralComponent.new(challenge_day: @challenge_day)) %>

app/views/challenge_days/photos/show.html.erb
<turbo-frame id="<%= dom_id(@challenge_day, 'photo') %>">
  <%= ('<img class="challenge-day-image img-fluid" src="data:image/jpg;base64,%s">' % Base64.encode64(@challenge_day.photo)).html_safe %>
</turbo-frame>

app/views/challenge_days/update.html.erb
<%= turbo_frame_tag dom_id(@challenge_day) do %>
  <% if @challenge_day.success? %>
    <%= render(ChallegeDayCompletedComponent.new(challenge_day: @challenge_day)) %>
  <% elsif @challenge_day.fail? %>
    <%= render(::ChallengeDay::ChallengeDayFailComponent.new(challenge_day: @challenge_day)) %>
  <% end %>
<% end %>

app/views/challenges/index.html.erb
<div class="container">
  <h1>All Challenges</h1>
  <div class="list-group">
    <% @challenges.each do |c| %>
        <%= link_to c.name, challenge_months_path(c), class: "list-group-item list-group-item-action" %>
    <% end %>
  </div>
</div>

app/views/challenges/months/index.html.erb
<div class="container">
  <h1><%= @challenge.name %></h1>
  <div class="list-group">
      <%= render(Challenges::MonthComponent.with_collection(@months, challenge: @challenge)) %>
  </div>
</div>

app/views/challenges/months/show.html.erb
<div class="container">
  <%= tag.h1 @challenge.name %>
  <%= render ChallengeDayComponent.with_collection(@challenge_days) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ctracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/create.html.erb
<turbo-frame id="hare-ram">
    <div class="log-displayer">
      <%= tag.h3 @message %>
      <%= tag.ul do %>
        <% dates(@commits).each do |date| %>
          <li><%= date %>:
            <ul>
              <% commits_on_date(date, @commits).each do |commit| %>
                <%= tag.li "#{message(commit)}, Author: #{author(commit)}" %>
              <% end %>
            </ul>
          </li>
        <% end %>
      <% end %>
    </div>
    <%= form_with url: logs_url do |f| %>
      <h3 class="row">
        <p>View commits from a specific date:</p>
      </h3>
      <div class='row'>
        <div class="col">
          <%= f.label :year %>
          <%= select_year Date.today, {}, class: "form-select" %>
        </div>
        <div class="col">
          <%= f.label :month %>
          <%= select_month Date.today, {}, class: "form-select" %>
        </div>
        <div class="col mb-2">
          <%= f.label :day %>
          <%= select_day Date.today, {}, class: "form-select"  %>
        </div>
        <%= f.submit "Show logs", class: 'btn btn-primary' %>
      </div>
    <% end %>
    <div class="row mt-3">
      <%= tag.button class: "btn btn-danger" do %>
        <%= link_to "reset", logs_path %>
      <% end %>
    </div>
  </turbo-frame>

app/views/logs/index.html.erb
<div class="container">
  <h1>View Logs</h1>
  <p>Repo name: <a href="https://github.com/binarygit/show-job">Show Job</a></p>
  <div class="log-displayer">
    <%= tag.p @message %>
    <%= tag.ul do %>
      <% dates(@commits).each do |date| %>
        <li><%= date %>:
          <ul>
            <% commits_on_date(date, @commits).each do |commit| %>
              <%= tag.li "#{message(commit)}, Author: #{author(commit)}" %>
            <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>
  </div>
  <%= form_with url: new_log_path do |f| %>
    <div class='row'>
      <div class="col">
        <%= f.label :year %>
        <%= select_year Date.today, {}, class: "form-select" %>
      </div>
      <div class="col">
        <%= f.label :month %>
        <%= select_month Date.today, {}, class: "form-select" %>
      </div>
      <div class="col mb-2">
        <%= f.label :day %>
        <%= select_day Date.today, {}, class: "form-select"  %>
      </div>
      <%= f.submit "Show logs", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>